### ISSUE TITLE
NewickError Unexisting tree file but I can find tree file

### ISSUE THREAD

**Issue by OliviaAgatha** [davidemms/OrthoFinder#768]
I ran Orthofinder.

Best outgroup(s) for species tree
---------------------------------
2022-11-28 16:11:52 : Starting STRIDE
Traceback (most recent call last):
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/stride.py", line 506, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/newick.py", line 216, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/__main__.py", line 1778, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/stride.py", line 509, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/olivia/anaconda3/envs/orthofinder_source/bin/scripts_of/newick.py", line 216, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

NOTE: I found tree_id.txt at .../Results_Nov29/WorkingDirectory/Tree_ids/

Please advice!
Thank you!

**Comment by davidemms** [comment]
Hi

I think you might be running an old version and this issue has been fixed in the latest version (2.5.4).

All the best
David

**Comment by OliviaAgatha** [comment]
Dear David,

I am running version 2.5.4 and this problem still occurs.

Please advice.

Thank you.

Regards,
Olivia
________________________________

**Comment by davidemms** [comment]
Hi Olivia

Could you paste the full log from the start of the run please, it may contain a clue as to what caused the problem.

All the best
David

**Comment by davidemms** [comment]
Hi @biology-han 

I've deleted your message as it is not relevant to this issue. If you have an issue could you please post it as a new issue and provide a full description of the problem, the information you've put here doesn't explain to me what the issue is that you have found.

Best wishes
David

**Comment by biology-han** [comment]
Hi David
Sorry for my question.&nbsp;I didn't pay attention to this problem.&nbsp;
My issue is https://github.com/davidemms/OrthoFinder/issues/765.&nbsp;
Please let me know if any other information is needed and thanks so much for any advice.
Best wishes
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davidemms/OrthoFinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davidemms/OrthoFinder] Version 2.5.4 NewickError Unexisting tree file but I can find tree file (Issue #768)





 
Hi @biology-han
 
I've deleted your message as it is not relevant to this issue. If you have an issue could you please post it as a new issue and provide a full description of the problem, the information you've put here doesn't explain to me what the issue is that you have found.
 
Best wishes
 David

**Comment by davidemms** [comment]
Hi

I think this might be because OrthoFinder needed an update to work with python 3.11. It was reported here and has now been resolved: https://github.com/davidemms/OrthoFinder/issues/782

Is that the same issue you were seeing?

Thanks
David

**Comment by OliviaAgatha** [comment]
Hi, I found out my error is caused because one of the inputs doesn't have a complete proteome.

Thank you.

Regards,
Olivia
________________________________
